### PR TITLE
Added Selection Sort and Multithreading concept in python

### PR DESCRIPTION
**Pull request by mastermanav09**

### CODE REVIEW

**Comment by mastermanav09** [comment]
please put a hacktoberfest20 label on the repo.. . Its necessary for the hacktoberfest.
Thank you !!

**Comment by mastermanav09** [comment]
Please put a hactoberfest20 label on the repo...

**Comment by Rutikab12** [comment]
done !

**Comment by mastermanav09** [comment]
hey !! spelling is wrong, you missed the k in hack (in the repo name and label both)

**Comment by Rutikab12** [comment]
Sorry! and thank you for reminding me

**Pull request merged**
